name: Release Translation

on:
    push:
        tags:
            - 'translation*'
        paths-ignore:
            - '**.md'

jobs:
    release-translation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  ref: crowdin
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '14.x'

            - run: sudo npm i -g @crowdin/cli
            - run: npm ci
            - run: npm run format
            - run: npm run test

            - uses: olegtarasov/get-tag@v2.1
              id: tagName

            - name: Extract, Upload and Download from Crowdin Platform
              run: |
                  branch_name="deriv-com-translations"

                  echo "Setting up Git identity"
                  git config --global user.name "DerivFE"
                  git config --global user.email "80095553+DerivFE@users.noreply.github.com"

                  echo "Installing Crowdin CLI"
                  sudo npm i -g @crowdin/cli
                  sudo npm ci

                  echo "Checking out new branch [$branch_name]"
                  git checkout -b "$branch_name"

                  echo "Running the translation script (extract-translations.js)"
                  sudo npm run translate:extract

                  echo "Downloading new strings to Crowdin"
                  sudo npm run translate:download -T ${{ secrets.CROWDIN_API_KEY }}
                  git add -A
                  git commit -am "Update Translations 📚 - $GIT_TAG_NAME"
                  git push origin HEAD:deriv-com-translations --force